# Version of the config.yml
version: "v2.0.0"

# Name of the challenge
name: "Integer Overflow - 101"

# Challenge difficulty: 10 - 500
difficulty: 10

enable_flag_input: true

flag: "b@$ic!nteger0verfl0w"

skills: ["Linux OS", "Assembly", "C"]

recommendations:
    https://en.wikipedia.org/wiki/Integer_overflow: 'Integer Overflow - Wikipedia'

# The emails of the Intellectual Property (IP) owners. Note that it is also possible that the owner is the same as the content creator.
owners: ["Avielyo10@gmail.com"]

# CRP Config
crp_config:
    controller:
        # Required Linux capabilities (See http://man7.org/linux/man-pages/man7/capabilities.7.html for the full list).
        # For example ["SETGID","SETUID"]
        #capabilities: [] # Not needed if empty
        ports: ['5555/controller']
    solvable:
        #capabilities: [] # Not needed if empty
        ports: ['8888/http']

